config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :channels

  get 'channels/:id/join_channel', to: "channels#join_channel"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  has_many :user_channelships, dependent: :destroy

  validates :topic, presence: true, uniqueness: true

  before_validation :topic_downcase

  protected

  def topic_downcase
    self.topic.downcase!
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages, dependent: :destroy
  has_many :user_channelships, dependent: :destroy
  has_many :channels, through: :user_channelships
  validates :username, presence: true

end

app/models/user_channelship.rb
class UserChannelship < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @channels = Channel.all
    @user = current_user
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      redirect_to @channel
    else
      flash[:error] = "Channel topic duplicated!"
      redirect_to :back
    end
  end

  def show
    @channel = Channel.find(params[:id])
    @message = Message.new
    @user_channelship = current_user.user_channelships.find_by(channel_id: params[:id])
    if @user_channelship.nil?
      @join = false
    else
      @join = true
      @user_channel = current_user.channels.find_by(id: params[:id])
      @read = @user_channelship.read
      @user_channelship.update :read => @channel.messages.last.try(:id) || 0
    end
  end

  def join_channel
    if current_user.channels.find_by(id: params[:id]).nil?
      current_user.user_channelships.create(channel_id: params[:id])
    end
    @channel = Channel.find(params[:id])
    redirect_to @channel
  end

  private

  def channel_params
    params.require(:channel).permit(:topic)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to channel_path(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def channel_lists
    current_user.channels.order(:topic)
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
  def unread user, channel
    return user.user_channelships.find_by(:channel_id => channel.id).read < (channel.messages.last.try(:id) || 0)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/channels/_channel.html.erb
<li>
  <%= content_tag :div, "data-channel-list-id" => channel.id do %>
  <% if unread current_user, channel %>
  <div class="unread-channel">
  <% else %>
  <div>
  <% end %>
    <%= link_to channel_path(channel) do %>
      <span class="link-wrapper"></span>
      # <%= "#{channel.topic}" %>
    <% end %>
  </div>
  <% end %>
</li>

app/views/channels/_show.js.erb
<script>
  $(function(){
    temp = "<%= id %>";
    $("[data-channel-list-id=" + "'" + temp + "'" + "]").children().first().addClass('current-channel');

    unread_height = $('.unread-msgs').height()+20;
    $('.unread-msgs').nextAll().each(function(){
        unread_height+=$(this).outerHeight(true);
    });
    $('.row-fluid').scrollTop($('.row-fluid').prop('scrollHeight')-unread_height);
  });
</script>

app/views/channels/index.html.erb
<div class="channels-browser">
    <div class="channels-browser-header">
        <h1>Browse all <%= @channels.size %> channels</h1>
        <%= link_to new_channel_path do %>
            <div class="button-ok">New Channel</div>
        <% end %>
    </div>
    <div class="channels-list-container">
        <div>
            <p>
            Channels you can join
            </p>
        </div>
        <% @channels.each do |channel| %>
            <% if @user.user_channelships.find_by(channel_id: channel.id).nil? %>
                <%= link_to channel_path(channel) do %>
                    <div class="channels-browser-row">
                        <%= "# #{channel.topic}" %>
                    </div>
                <% end %>
            <% end %>
        <% end %>
        <div>
            <p>
            Channels you belong to
            </p>
        </div>
        <% @channels.each do |channel| %>
            <% unless @user.user_channelships.find_by(channel_id: channel.id).nil? %>
                <%= link_to channel_path(channel) do %>
                    <div class="channels-browser-row">
                        <%= "# #{channel.topic}" %>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/channels/new.html.erb
<div class="channels-form-container">
    <div class="channels-form">
        <h2>Create a Channel</h2>
        <%= form_for @channel, remote: true do |f| %>
            <div class="field">
                <%= f.label :topic %><br />
                <%= f.text_field :topic, autofocus: true %>
            </div>
            <div class="actions">
                <%= f.submit "Create Channel", :class => "button-ok"%>
            </div>
        <% end %>
    </div>
</div>

app/views/channels/show.html.erb
<!--<div>
  <h1># <%= @channel.topic %></h1>
  <div>
    <% if @channel.messages.any? %>
    <div id="messages" data-channel-id="<%=@channel.id%>">
      <%= render partial: 'messages/message', collection: @channel.messages.includes(:user) %>
    </div>
    <% else %>
    <div class="hidden" id="messages" data-channel-id="<%=@channel.id%>">
      <p>
        Be the First to Chat!
      </p>
    </div>
    <% end %>
  </div>
  <%= render partial: 'messages/message_form', locals: {message: @message, channel: @channel} %>
</div>-->

<div class="client-main-container">
  <header id="client-header">
    <%# <div id="active-channel-name-overlay"></div> %>
    <div class="channel-header">
      <div class="messages-header">
        <div class="channel-title">
          <h2 id="channel-name-container" class="channel-name-container">
          <span id="channel-name" class="channel-name">
            <span id="channel-title">
              #<%= @channel.topic %>
            </span>
          </span>
          <%# <div class="channel-actions-container">                %>
            <%#     <a id="mute-container" class="mute-container"></a> %>
          <%# </div>                                                 %>
          </h2>
          <%# <div id="channel-header-info">                                     %>
            <%#     <div id="star-container" class="star-container"></div>         %>
            <%#     <span class="topic-divider">|</span>                           %>
            <%#     <span id="channel-members-toggle-count"></span>                %>
            <%#     <span id="pinned-count-divider" class="topic-divider">|</span> %>
            <%#     <span id="pinned-item-count"></span>                           %>
            <%#     <span class="topic-divider"></span>                            %>
            <%#     <span id="topic-inline-edit" class="change-topic"></span>      %>
          <%# </div>                                                             %>
        </div>
        <%# <div class="channel-title-info">                  %>
          <%#     <div id="channel-calls-container"></div>      %>
          <%#     <button id="channel-actions-toggle"></button> %>
          <%#     <button id="details-toggle"></button>         %>
          <%#     <div class="divider-bar"></div>               %>
        <%# </div>                                            %>
      </div>
      <%# <div class="flex-header">                                                                                      %>
        <%#     <div id="search-container">                                                                                %>
          <%#         <form id="header-search-form" class="search-form" action="">                                           %>
            <%#             <div class="icon-search-wrap"></div>                                                               %>
            <%#             <input type="text" id="search-terms" class="search-input" placeholder="Search" autocomplete="off"> %>
            <%#             <div class="search-clear-icon-wrap">                                                               %>
              <%#                 <a id="search-clear" class="search-clear-icon"></a>                                            %>
            <%#             </div>                                                                                             %>
          <%#         </form>                                                                                                %>
        <%#     </div>                                                                                                     %>
        <%#     <button id="recent-mentions-toggle"></button>                                                              %>
        <%#     <button id="stars-toggle"></button>                                                                        %>
        <%#     <button id="flex-menu-toggle">                                                                             %>
        <%#         <div id="whats-new-burst"></div>                                                                       %>
        <%#     </button>                                                                                                  %>
        <%#     <button id="whats-new-toggle"></button>                                                                    %>
        <%#     <div id="rxn-toast-div"></div>                                                                             %>
      <%# </div>                                                                                                         %>
    </div>
  </header>
  <div id="client-body" data-channel-id="<%=@channel.id%>">
    <div id="col-messages">
      <div id="footer">
        <%# <div id="footer-overlay"></div> %>
        <div id="footer-msgs">
          <%# <div id="msg-preview">                               %>
            <%#     <div id="msg-preview-msg" class="message"></div> %>
          <%# </div>                                               %>
          <% if not @join %>
          <div>
            <%= link_to "Join Channel", "#{@channel.id}/join_channel", :class => "button-ok", :id => "join-channel-btn"%>
          </div>
          <% else %>
          <div id="messages-input-container">
            <!--
            <%# <a id="primary-file-button" class="file-upload-btn"></a> %>
            <form id="message-form">
              <textarea id="message-input" name=""></textarea>
              <div id="message-input-message"></div>
              <%# <input id="file-upload" type=""> %>
            </form>
            -->
            <%= render partial: 'messages/message_form', locals: {message: @message, channel: @channel} %>
          </div>
          <% end %>
          <%# <div id="notification-bar">                  %>
            <%#     <div id="typing-text"></div>             %>
            <%#     <div id="special-formatting-text"></div> %>
            <%#     <div id="snippet-prompt">                %>
              <%#         <div class="warning"></div>          %>
            <%#     </div>                                   %>
          <%# </div>                                       %>
        </div>
        <%# <div id="footer-archives">                          %>
          <%#     <div id="footer-archives-table">                %>
            <%#         <div id="footer-archives-left">             %>
              <%#             <span id="footer-archives-text"></span> %>
            <%#         </div>                                      %>
            <%#         <div id="footer-archives-right"></div>      %>
          <%#     </div>                                          %>
        <%# </div>                                              %>
      </div>
      <div class="row-fluid">
        <div id="messages-container">
          <%# <div id="unread-msgs-scroller-div"></div> %>
          <%# <div id="archive-msgs-scroller-div">      %>
            <%#     <div id="archives-top-div"></div>     %>
            <%#     <div id="archives-msgs-div"></div>    %>
            <%#     <div id="archives-bottom-div"></div>  %>
          <%# </div>                                    %>
          <div id="msgs-scroller-div">
            <div id="end-div"></div>
            <div id="msgs-div">
              <div class="day-container">
                <div class="day-divider">
                  <%#<div class="day-divider-label">Test Day Divider</div>%>
                </div>
                <% @have_unread = false %>
                <%= render partial: 'messages/message', collection: @channel.messages.includes(:user) %>
              </div>
            </div>
            <%# <div id="msgs-overlay-div"></div> %>
          </div>
          <%# <div id="messages-unread-status"></div> %>
          <%# <div id="file-progress"></div>          %>
          <%# <div id="connection-div"></div>         %>
          <%# <div id="archives-return"></div>        %>
        </div>
      </div>
    </div>
    <%# <div id="col-flex">                                  %>
      <%#     <div id="flex-contents">                         %>
        <%#         <div id="stars-tab" class="panel">           %>
          <%#             <div class="heading"></div>              %>
          <%#             <div id="stars-scroller"></div>          %>
        <%#         </div>                                       %>
        <%#         <div id="mentions-tab" class="panel"></div>  %>
        <%#         <div id="files-tab" class="panel"></div>     %>
        <%#         <div id="team-tab" class="panel"></div>      %>
        <%#         <div id="search-tab" class="panel"></div>    %>
        <%#         <div id="details-tab" class="panel"></div>   %>
        <%#         <div id="downloads-tab" class="panel"></div> %>
        <%#         <div id="whats-new-tab" class="panel"></div> %>
      <%#     </div>                                           %>
    <%# </div>                                               %>
  </div>
</div>
<%= render :partial => 'show.js', locals: {id: @channel.id} %>

app/views/common/_sidebar.html.erb
<div class="client-channels-list-container">
    <div id="col-channels-bg"></div>
    <%# <div id="col-channels-overlay"></div> %>
    <div id="team-menu">
        <%# <div class="placeholder-shimmer-clipper">          %>
        <%#     <div class="placeholder-shimmer-bg-wrapper">   %>
        <%#         <div class="placeholder-shimmer-bg"></div> %>
        <%#     </div>                                         %>
        <%# </div>                                             %>
        <%# <button class="notifications-menu-btn"></button>   %>
        <div class="team-name-container">
            <%# <button class="team-name-caret"></button> %>
            <span id="team-name">Slacc</span>
        </div>
        <%# <div id="team-menu-overlay">              %>
        <%#     <div class="overlay-mock-text"></div> %>
        <%# </div>                                    %>
        <%= link_to destroy_user_session_path, :method => :delete do %>
          <div id="presence-container"><i id="presence"></i></div>
        <% end %>
        <span id="team-header-user-name" class="current-user-name"><%= current_user.username %></span>
    </div>
    <div id="col-channels" class="channels-list-holder">
        <%# <div class="placeholder-shimmer-clipper">          %>
        <%#     <div class="placeholder-shimmer-bg-wrapper">   %>
        <%#         <div class="placeholder-shimmer-bg"></div> %>
        <%#     </div>                                         %>
        <%# </div>                                             %>
        <div id="channels-nav"></div>
        <div id="channels-scroller">
            <%# <ul id="all-unreads-list"></ul>                %>
            <%# <div id="unread" role="navigation"></div>      %>
            <%# <div id="starred-div" role="navigation"></div> %>
            <div id="channels" role="navigation">
                <%= link_to "+", new_channel_path, :class => "channels-list-new-btn link-unstyle" %>
                <h2 id="channels-header" class="hoverable">
                    <%= link_to channels_path do %>
                        <span class="link-wrapper"></span>
                    <% end %>
                    <button class="channel-list-header-label btn-unstyle">Channels
                        <span class="header-count">(
                            <span id="channel-header-count"><%= channels.size %></span>
                            )</span>
                    </button>
                </h2>
                <ul id="channel-list">
                    <%= render partial: 'channels/channel', collection: channels %>
                </ul>
            </div>
            <%# <div id="direct-messages" role="navigation"></div>                             %>
            <%# <button id="channel-list-invites-link" class="channel-list-add-link"></button> %>
            <%# <div id="everything"></div>                                                    %>
        </div>
        <%# <a id="channel-scroll-up"></a>          %>
        <%# <a id="channel-scroll-down"></a>        %>
        <%# <div id="col-channels-footer">          %>
            <%#     <div id="quick-switcher-btn"></div> %>
            <%# </div>                                  %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Slacc</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <div class="notification-banner">
          <% flash.each do |key, value| %>
            <%= content_tag :div, value, :class => "flash #{key}" unless value.blank? %>
          <% end %>
        </div>
        <% if !user_signed_in? %>
            <%= yield %>
        <% else %>
            <div id="client-ui">
                <div class="client-container">
                    <%= render partial: "common/sidebar", locals: { :channels => channel_lists } %>
                    <%= yield %>
                </div>
            </div>
        <% end %>
    </body>
</html>

app/views/messages/_message.html.erb
<% if @join and !@have_unread and @read < message.id %>
  <% @have_unread = true %>
  <div class="unread-msgs">
    <div class="unread-msgs-label">
      Unread Messages
    </div>
  </div>
<% end %>
<div class="day-msgs">
  <ts-message class="message">
  <div class="message-gutter">
    <%= image_tag("doge.jpg", :alt => "doge") %>
  </div>
  <div class="message-content">
    <div class="message-content-header"><%= message.user.username %></div>
    <div class="message-content-time"><%= message.created_at.strftime("%I:%M %p") %></div>
    <div class="message-body"><%= simple_format message.content %></div>
  </div>
  </ts-message>
</div>

app/views/messages/_message_form.html.erb
<textarea id="message-input" data-textarea="message" name="message[content]"></textarea>
<input type="submit" name="commit" value="send" style="display: none" data-send="message" data-disable-with="send" />